routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});

Auth::routes(['verify' => true]);

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('/trip', 'TripController')->except(['show', 'index']);
    Route::group(['middleware' => ['verified']], function () {
        Route::resource('/team', 'TeamController');
    });
});

// Make trips visible to the public
Route::get('/trip/{trip}', 'TripController@show');
    // Just testing this middleware, checks if the user has a traveler assigned to the trip.
    //  ->middleware('can:view,trip');

app/Address.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Address extends Model {

    protected $guarded = [ 'id' ];

    public function addressable() {
        return $this->morphTo();
    }

    public function getOneLineAttribute() {
        return $this->line_1 . ', ' . ($this->line_2 ? $this->line_2 . ', ' : '') . $this->state . ' ' . $this->zip;
    }
}

resources/views/partials/hero.blade.php
<div class="flex-none w-100">
    <div
            class="h-{{ $height ?? 64 }} p-4 flex-grow flex flex-col justify-end content-end items-start"
            style="
                    background: url('{{ asset('images/liam-pozz-455682-unsplash.jpg') }}') no-repeat center center fixed;
                    background-size: cover;
                    "
    >
        <div class="container mx-auto max-w-md">
            <div class="text-white font-raleway font-hairline text-xl">{{ $line_1 ?? 'Hi There!' }}</div>
            <div class="text-white font-raleway font-normal text-3xl">{{ $line_2 ?? 'Welcome To TripStar' }}</div>
        </div>
    </div>
</div>

resources/views/partials/navbar.blade.php
<nav class="flex-none bg-blue py-6 px-3">
    <div class="container flex items-center justify-between flex-wrap mx-auto m-w-lg">
        <a href="{{ url('/') }}">
            <div class="flex items-center flex-no-shrink text-white mr-6">
                @svg('solid/jedi', ['class' => 'icon fill-current h-8 w-8 mr-2'])
                <span class="text-white font-semibold text-xl tracking-tight">TripStar</span>
            </div>
        </a>
        @guest
        @if(Route::is('login'))
            <div>
                <a href="{{ route('register') }}"
                   class="no-underline inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-blue hover:bg-white lg:mt-0">Register</a>
            </div>
        @else
            <div>
                <a href="{{ route('login') }}"
                   class="no-underline inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-blue hover:bg-white lg:mt-0">Login</a>
            </div>
        @endif
        @endguest
        @auth
        <div class="block lg:hidden">
            <button id="toggleNav"
                    class="flex items-center px-3 py-2 border rounded text-blue-lightest border-blue-lightest hover:text-white hover:border-white">
                @svg('solid/bars', ['class' => 'icon fill-current h-3 w-3'])
            </button>
        </div>
        <div id="expand" class="w-full block flex-grow lg:flex lg:items-center lg:w-auto hidden">
            <div class="text-sm lg:flex-grow">
                <a href="{{ action('HomeController@index') }}"
                   class="navbar-link lg:inline-block lg:mt-0">
                    Dashboard
                </a>
                <a href="{{ action('TripController@create') }}"
                   class="navbar-link lg:inline-block lg:mt-0">
                    New Trip
                </a>
            </div>
            <div>
                <form action="{{ route('logout') }}" method="POST">
                    @csrf
                    <button class="no-underline inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-blue hover:bg-white mt-4 lg:mt-0">
                        Logout
                    </button>
                </form>
            </div>
        </div>
        @endauth
    </div>
</nav>

@section('scripts')
    <script>
        $('#toggleNav').click(function () {
            $('#expand').toggleClass('hidden');
        });
    </script>
@append

resources/views/partials/trip-hero.blade.php
<div class="flex-none w-100">
    <div
            class="h-{{ $height ?? 64 }} p-4 flex-grow flex flex-col justify-end content-end items-start"
            style="background: linear-gradient(to bottom, rgba(0,0,0,0.2), rgba(0,0,0,0.4)), url('{{ asset("images/{$trip->image}") }}') no-repeat center center;
                    background-size: cover;"
    >
        <div class="h-full container mx-auto max-w-md">
            <div class="h-full flex flex-col justify-between">
                <div>
                    <img class="h-16" src="{{ asset("images/{$trip->team->logo}") }}" alt="">
                    <div class="text-white font-raleway font-normal text-xl">{{ $trip->team->display_name }}</div>
                </div>
                <div>
                    <div class="text-white font-raleway font-normal text-2xl">{{ $trip->name }}</div>
                    <div class="text-white font-raleway font-hairline text-lg">{{ $trip->address->one_line ?? "Add an address!" }}</div>
                </div>
            </div>
        </div>
    </div>
</div>