routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});

Auth::routes(['verify' => true]);

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('/trip', 'TripController')->except(['show', 'index']);
    Route::group(['middleware' => ['verified']], function () {
        Route::resource('/team', 'TeamController');
    });
});

// Make trips visible to the public
Route::get('/trip/{trip}', 'TripController@show');
    // Just testing this middleware, checks if the user has a traveler assigned to the trip.
    //  ->middleware('can:view,trip');

app/Trip.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Spatie\SchemalessAttributes\SchemalessAttributes;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;
use Illuminate\Database\Eloquent\Model;

class Trip extends Model {

    use HasSlug;

    protected $guarded = [ 'id' ];

    protected $casts = [
        'options' => 'array',
        'depart_at' => 'datetime',
        'return_at' => 'datetime'
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'depart_at',
        'return_at',
    ];

    public function setDepartAtAttribute($value) {
        $this->attributes['depart_at'] = Carbon::parse($value)->toDateTimeString();
    }

    public function setReturnAtAttribute($value) {
        $this->attributes['depart_at'] = Carbon::parse($value)->toDateTimeString();
    }

    public function getSlugOptions() : SlugOptions {
        return SlugOptions::create()
                          ->generateSlugsFrom('name')
                          ->saveSlugsTo('slug');
    }

    public function getExtraAttributesAttribute() : SchemalessAttributes {
        return SchemalessAttributes::createForModel($this, 'options');
    }

    public function scopeWithExtraAttributes() : Builder {
        return SchemalessAttributes::scopeWithSchemalessAttributes('options');
    }

    public function address() {
        return $this->morphOne(Address::class, 'addressable');
    }

    public function team() {
        return $this->belongsTo(Team::class);
    }

    public function invites() {
        return $this->morphMany(Invite::class, 'invitable');
    }

    public function travelers() {
        return $this->belongsToMany(Traveler::class);
    }

    public function scopeFuture($query) {
        return $query->where('depart_at', '>', Carbon::now());
    }

    public function scopePast( $query ) {
        return $query->where('return_at', '<', Carbon::now());
    }

    public function scopeCurrent( $query ) {
        return $query
            ->where('depart_at', '<', Carbon::now())
            ->where('return_at', '>', Carbon::now());
    }

    public function invitedTravelers(  ) {
        return $this->morphMany(Invite::class, 'invitable');
    }

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }
}

app/Http/Controllers/TripController.php
<?php

namespace App\Http\Controllers;

use App\Address;
use App\Trip;
use Carbon\Carbon;
use Illuminate\Http\Request;

class TripController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        return view('trips.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store( Request $request ) {
        $validatedTrip    = $request->validate([
                                                   // TODO allow the teams that they belong to for Team ID
                                                   'team_id'     => 'required',
                                                   'image'       => 'required|image',
                                                   'name'        => 'required|max:255',
                                                   'description' => 'string|max:65500',
                                                   'price'       => 'integer|max:65000',
                                                   'depart_at'   => 'required|before:return_at',
                                                   'return_at'   => 'nullable|after:depart_at',
                                               ]);

        $validatedAddress = $request->validate([
                                                   'line_1'  => 'required|string|max:255',
                                                   'line_2' => 'string|max:255',
                                                   'city'     => 'required|string|max:255',
                                                   'state'    => 'required|string|max:255',
                                                   'zip'      => 'required|string',
                                               ]);

        if($request->hasFile('image') && $request->file('image')->isValid()) {
            $path                 = $request->image->store('images', 'public');
            $validatedTrip[ 'image' ] = $path;
        }

        // Make the name of the address the trip name
        $validatedAddress['name'] = $validatedTrip['name'];
        $trip = Trip::create($validatedTrip);

        $validatedAddress['addressable_type'] = get_class($trip);
        $validatedAddress['addressable_id'] = $trip->id;
        Address::create($validatedAddress);

        return redirect("/trip/{$trip->slug}");

    }

    /**
     * Display the specified resource.
     *
     * @param \App\Trip $trip
     *
     * @return \Illuminate\Http\Response
     */
    public function show( Trip $trip ) {
        return view('trips.show', compact('trip'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit( $id ) {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int                      $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update( Request $request, $id ) {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy( $id ) {
        //
    }
}

resources/views/trips/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="flex text-grey-darker flex-col flex-grow font-roboto">
        @component('partials.hero')
            @slot('height') 64 @endslot
            @slot('line_2') Create an Event @endslot
        @endcomponent
        <div class="p-3">
            <form enctype="multipart/form-data" action="{{ route('trip.store') }}" method="POST" class="w-full max-w-md container mx-auto">
                @csrf
                @include('trips.fields')
                <button class="btn btn-blue">Save</button>
            </form>
        </div>
    </div>
@endsection

resources/views/trips/fields.blade.php
<div class="flex flex-wrap -mx-3 mb-6">
    <div class="w-full px-3 mb-6 md:mb-0">
        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="name">
            Trip Name
        </label>
        <input autofocus
               value="{{ old('name') }}"
               name="name"
               class="input @if(count($errors->get('name'))) border-red @endif"
               id="name"
               type="text"
               placeholder="Your name here...">
        @if(count($errors->get('name')))
            @foreach($errors->get('name') as $message)
                <p class="text-red text-xs italic">{{ $message }}</p>
            @endforeach
        @endif
    </div>
    <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="team_id">
            Your Team
        </label>
        <div class="relative">
            <select name="team_id"
                    class="block appearance-none w-full bg-grey-lighter border border-grey-lighter text-grey-darker py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-grey @if(count($errors->get('team'))) border-red @endif" id="team">
                @foreach(\App\Team::get() as $team)
                    <option value="{{ $team->id }}">{{ $team->display_name }}</option>
                @endforeach
            </select>
            <div class="pointer-events-none absolute pin-y pin-r flex items-center px-2 text-grey-darker">
                @svg('solid/angle-down', ['class' => 'fill-current h-4 w-4'])
            </div>
        </div>
        @if(count($errors->get('price')))
            @foreach($errors->get('price') as $message)
                <p class="text-red text-xs italic">{{ $message }}</p>
            @endforeach
        @endif
    </div>
    <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
        <label class="block text-grey-darker text-sm font-bold mb-2" for="price">
            Trip Price
        </label>
        <input  value="{{ old('price') }}"
                name="price"
                class="input @if(count($errors->get('price'))) border-red @endif"
                id="price"
                type="number" step=".01"
                placeholder="Your price here...">
        @if(count($errors->get('price')))
            @foreach($errors->get('price') as $message)
                <p class="text-red text-xs italic">{{ $message }}</p>
            @endforeach
        @endif
    </div>
    <div class="w-full px-3 mb-6 md:mb-0">
        <label class="block text-grey-darker text-sm font-bold mb-2" for="description">
            Your Description
        </label>
        <textarea  name="description"
                   class="input @if(count($errors->get('description'))) border-red @endif"
                   id="description"
                   type="text"
                   rows="5"
                   placeholder="Your description here...">{{ old('description') }}</textarea>
        @if(count($errors->get('description')))
            @foreach($errors->get('description') as $message)
                <p class="text-red text-xs italic">{{ $message }}</p>
            @endforeach
        @endif
    </div>
    <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
        <label class="block text-grey-darker text-sm font-bold mb-2" for="depart_at">
            Your Trip's Departure Time
        </label>
        <input  value="{{ old('depart_at') }}"
                name="depart_at"
                class="input @if(count($errors->get('depart_at'))) border-red @endif"
                id="depart_at"
                type="text"
                placeholder="Your departure time here...">
        @if(count($errors->get('depart_at')))
            @foreach($errors->get('depart_at') as $message)
                <p class="text-red text-xs italic">{{ $message }}</p>
            @endforeach
        @endif
    </div>
    <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
        <label class="block text-grey-darker text-sm font-bold mb-2" for="return_at">
            Your Trip's Return Time
        </label>
        <input  value="{{ old('return_at') }}"
                name="return_at"
                class="input @if(count($errors->get('return_at'))) border-red @endif"
                id="return_at"
                type="text"
                placeholder="Your return time here...">
        @if(count($errors->get('return_at')))
            @foreach($errors->get('return_at') as $message)
                <p class="text-red text-xs italic">{{ $message }}</p>
            @endforeach
        @endif
    </div>
    <div class="w-full px-3 my-6">
        <label class="w-full flex flex-col items-center px-4 py-6 bg-white text-blue rounded-lg shadow-lg tracking-wide uppercase border @if(count($errors->get('image'))) border-red @else border-blue @endif cursor-pointer hover:bg-blue hover:text-white">
            @svg('solid/cloud-upload-alt')
            <span class="mt-2 text-base leading-normal">Select Trip Image</span>
            <input name="image" type='file' class="hidden" />
        </label>
        @if(count($errors->get('image')))
            @foreach($errors->get('image') as $message)
                <p class="text-red text-xs italic pt-3">{{ $message }}</p>
            @endforeach
        @endif
    </div>
    <div class="w-full px-3 mb-6 md:mb-0">
        <label class="block text-grey-darker text-sm font-bold mb-2" for="line_1">
            Your Destination
        </label>
        <input  value="{{ old('line_1') }}"
                name="line_1"
                class="input @if(count($errors->get('line_1'))) border-red @endif"
                id="line_1"
                type="text"
                placeholder="Where are we going?">
        @if(count($errors->get('line_1')))
            @foreach($errors->get('line_1') as $message)
                <p class="text-red text-xs italic">{{ $message }}</p>
            @endforeach
        @endif
    </div>
    <div class="w-full px-3 mb-6 md:mb-0">
        <label class="block text-grey-darker text-sm font-bold mb-2" for="line_2">
            Suite/Apt
        </label>
        <input  value="{{ old('line_2') }}"
                name="line_2"
                class="input @if(count($errors->get('line_2'))) border-red @endif"
                id="line_2"
                type="text"
                placeholder="Your Suite/Apt Here...">
        @if(count($errors->get('line_2')))
            @foreach($errors->get('line_2') as $message)
                <p class="text-red text-xs italic">{{ $message }}</p>
            @endforeach
        @endif
    </div>
    <div class="w-full md:w-2/3 px-3 mb-6 md:mb-0">
        <label class="block text-grey-darker text-sm font-bold mb-2" for="city">
            Your City
        </label>
        <input  value="{{ old('city') }}"
                name="city"
                class="input @if(count($errors->get('city'))) border-red @endif"
                id="city"
                type="text"
                placeholder="Your city Here...">
        @if(count($errors->get('city')))
            @foreach($errors->get('city') as $message)
                <p class="text-red text-xs italic">{{ $message }}</p>
            @endforeach
        @endif
    </div>
    <div class="w-full w-1/2 md:w-1/6 px-3 mb-6 md:mb-0">
    <label class="block text-grey-darker text-sm font-bold mb-2" for="state">
        Your state
    </label>
    <input  value="{{ old('state') }}"
            name="state"
            class="input @if(count($errors->get('state'))) border-red @endif"
            id="state"
            type="text"
            placeholder="Your state Here...">
    @if(count($errors->get('state')))
        @foreach($errors->get('state') as $message)
            <p class="text-red text-xs italic">{{ $message }}</p>
        @endforeach
    @endif
    </div>
    <div class="w-full w-1/2 md:w-1/6 px-3 mb-6 md:mb-0">
        <label class="block text-grey-darker text-sm font-bold mb-2" for="zip">
            Your zip
        </label>
        <input  value="{{ old('zip') }}"
                name="zip"
                class="input @if(count($errors->get('zip'))) border-red @endif"
                id="zip"
                type="text"
                placeholder="Your zip Here...">
        @if(count($errors->get('zip')))
            @foreach($errors->get('zip') as $message)
                <p class="text-red text-xs italic">{{ $message }}</p>
            @endforeach
        @endif
    </div>
</div>

@section('scripts')
    <script src="https://cdn.jsdelivr.net/npm/places.js@1.14.0"></script>
    <script>
        (function() {
            var placesAutocomplete = places({
//                appId: 'plVWWLQODWJN',
                apiKey: 'efda34499c5c9a6484b809eb95ce131b',
                container: document.querySelector('#line_1'),
                templates: {
                    value: function(suggestion) {
                        return suggestion.name;
                    }
                }
            }).configure({
                type: 'address'
            });
            placesAutocomplete.on('change', function resultSelected(e) {
                document.querySelector('#state').value = e.suggestion.administrative || '';
                document.querySelector('#city').value = e.suggestion.city || '';
                document.querySelector('#zip').value = e.suggestion.postcode || '';
            });
        })();
    </script>

    <script>
        new flatpickr("#depart_at", {
            disableMobile: false,
            enableTime: true,
            dateFormat: 'Z',
            altInput: true,
            altFormat: 'Y-m-d h:i K',
//            defaultDate: new Date(),
        });

        new flatpickr("#return_at", {
            disableMobile: false,
            enableTime: true,
            dateFormat: 'Z',
            altInput: true,
            altFormat: 'Y-m-d h:i K',
//            defaultDate: new Date(),
        });
    </script>
@endsection

resources/views/trips/show.blade.php
@php
    setlocale(LC_MONETARY, 'en_US.UTF-8');
@endphp

@extends('layouts.app')

@section('content')
    <div class="flex text-grey-darker flex-col flex-grow font-roboto">
        @component('partials.trip-hero', compact('trip'))
        @endcomponent
        <div class="flex justify-center py-6 px-2 bg-blue">
            <button class="btn btn-blue shadow-lg mr-3">Pay Now</button>
            <button class="btn btn-blue text-grey-light">Payment Options</button>
        </div>
        <div class="bg-grey-lighter border-b border-grey">
            <div class="w-full flex justify-between py-6 px-2 container mx-auto max-w-sm">
                <div class="flex flex-col justify-between">
                    <div class="text-blue text-sm p-1">Trip Name</div>
                    <div class="p-1">{{ $trip->name }}</div>
                </div>
                <div class="flex flex-col justify-between">
                    <div class="text-blue text-sm p-1">Travelers</div>
                    <div class="p-1">{{ $trip->travelers()->count() }}</div>
                </div>
                <div class="flex flex-col justify-between">
                    <div class="text-blue text-sm p-1">Departure</div>
                    <div class="p-1">{{ $trip->depart_at->format('M d g:ia') }}</div>
                </div>
            </div>
        </div>
        <div class="flex-grow">
            <div class="w-full flex flex-col py-6 px-2 justify-between container mx-auto max-w-sm">
                <div class="flex flex-col justify-between pb-2">
                    <div class="text-blue text-sm p-1">Description</div>
                    <div class="p-1">{{ $trip->description }}</div>
                </div>
                <div class="flex flex-col justify-between pb-2">
                    <div class="text-blue text-sm p-1">Trip Pricing</div>
                    <div class="p-1">{{ money_format('%.2n', $trip->price) }}</div>
                </div>
                @if($trip->travelers()->count() > 0)
                    <div class="flex flex-col justify-between pb-2">
                        <div class="text-blue text-sm p-1">Travelers</div>
                        <div class="p-1">
                            @foreach($trip->travelers as $traveler)
                                @if($loop->last)
                                    {{ $traveler->display_name }}
                                @else
                                    {{ $traveler->display_name }},
                                @endif
                            @endforeach
                        </div>
                    </div>
                @endif
                @if($trip->invitedTravelers()->count() > 0 && !Auth::guest())
                    <div class="flex flex-col justify-between pb-2">
                        <div class="text-blue text-sm p-1">Invited</div>
                        <div class="p-1">
                            @foreach($trip->invitedTravelers as $invite)
                                @if($loop->last)
                                    {{ $invite->email }}
                                @else
                                    {{ $invite->email }},
                                @endif
                            @endforeach
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection